DATA_SOURCE_LABELS = {
    "fred": "FRED",
    "yfinance": "Yahoo Finance",
    "mof_jgb": "財務省",
    "us_jp_yield_spread": "FRED・財務省",
}


INDICATORS = {
    "CPI": {
        "source": "fred",
        "ticker": "CPIAUCSL",
        "unit": "指数",
        "yoy": True,
        "correlation_method": "monthly_change",
        "category": "米国経済指標",
    },
    "FF金利": {
        "source": "fred",
        "ticker": "FEDFUNDS",
        "unit": "%",
        "yoy": False,
        "correlation_method": "monthly_change",
        "category": "米国経済指標",
    },
    "失業率": {
        "source": "fred",
        "ticker": "UNRATE",
        "unit": "%",
        "yoy": False,
        "correlation_method": "monthly_change",
        "category": "米国経済指標",
    },
    "USD/JPY": {
        "source": "yfinance",
        "ticker": "JPY=X",
        "unit": "円",
        "yoy": False,
        "category": "為替",
    },
    "日経平均株価": {
        "source": "yfinance",
        "ticker": "^N225",
        "unit": "円",
        "yoy": False,
        "category": "マーケット",
    },
    "日経平均先物": {
        "source": "yfinance",
        "ticker": "NKD=F",
        "unit": "円",
        "yoy": False,
        "category": "マーケット",
    },
    "S&P 500指数": {
        "source": "yfinance",
        "ticker": "^GSPC",
        "unit": "ポイント",
        "yoy": False,
        "category": "マーケット",
    },
    "NASDAQ総合指数": {
        "source": "yfinance",
        "ticker": "^IXIC",
        "unit": "ポイント",
        "yoy": False,
        "category": "マーケット",
    },
    "SOX指数": {
        "source": "yfinance",
        "ticker": "^SOX",
        "unit": "ポイント",
        "yoy": False,
        "category": "マーケット",
        "fallbacks": [
            {
                "source": "yfinance",
                "ticker": "SOXX",
                "unit": "米ドル",
                "label": "iShares Semiconductor ETF（近似）",
            }
        ],
    },
    "VIX指数": {
        "source": "yfinance",
        "ticker": "^VIX",
        "unit": "ポイント",
        "yoy": False,
        "category": "マーケット",
    },
    "WTI原油先物": {
        "source": "yfinance",
        "ticker": "CL=F",
        "unit": "米ドル",
        "yoy": False,
        "category": "マーケット",
    },
    "Gold先物": {
        "source": "yfinance",
        "ticker": "GC=F",
        "unit": "米ドル",
        "yoy": False,
        "category": "マーケット",
    },
    "TOPIX連動ETF（1306）": {
        "source": "yfinance",
        "ticker": "1306.T",
        "unit": "円",
        "yoy": False,
        "category": "マーケット",
    },
    "BTCｰJPY": {
        "source": "yfinance",
        "ticker": "BTC-JPY",
        "unit": "円",
        "yoy": False,
        "category": "マーケット",
    },
    "EUR/JPY": {
        "source": "yfinance",
        "ticker": "EURJPY=X",
        "unit": "円",
        "yoy": False,
        "category": "為替",
    },
    "AUD/JPY": {
        "source": "yfinance",
        "ticker": "AUDJPY=X",
        "unit": "円",
        "yoy": False,
        "category": "為替",
    },
    "MXN/JPY": {
        "source": "yfinance",
        "ticker": "MXNJPY=X",
        "unit": "円",
        "yoy": False,
        "category": "為替",
    },
    "CHF/JPY": {
        "source": "yfinance",
        "ticker": "CHFJPY=X",
        "unit": "円",
        "yoy": False,
        "category": "為替",
    },
    "AUD/MXN": {
        "source": "yfinance",
        "ticker": "AUDMXN=X",
        "unit": "メキシコペソ",
        "yoy": False,
        "category": "為替",
    },
    "MXN/CHF": {
        "source": "yfinance",
        "ticker": "MXNCHF=X",
        "unit": "スイスフラン",
        "yoy": False,
        "category": "為替",
    },
    "キオクシア（285A）": {
        "source": "yfinance",
        "ticker": "285A.T",
        "unit": "円",
        "yoy": False,
        "category": "注目銘柄",
    },
    "東京エレクトロン（8035）": {
        "source": "yfinance",
        "ticker": "8035.T",
        "unit": "円",
        "yoy": False,
        "category": "注目銘柄",
    },
    "レーザーテック（6920）": {
        "source": "yfinance",
        "ticker": "6920.T",
        "unit": "円",
        "yoy": False,
        "category": "注目銘柄",
    },
    "ディスコ（6146）": {
        "source": "yfinance",
        "ticker": "6146.T",
        "unit": "円",
        "yoy": False,
        "category": "注目銘柄",
    },
    "アドバンテスト（6857）": {
        "source": "yfinance",
        "ticker": "6857.T",
        "unit": "円",
        "yoy": False,
        "category": "注目銘柄",
    },
    "三菱商事（8058）": {
        "source": "yfinance",
        "ticker": "8058.T",
        "unit": "円",
        "yoy": False,
        "category": "注目銘柄",
    },
    "三菱UFJ（8306）": {
        "source": "yfinance",
        "ticker": "8306.T",
        "unit": "円",
        "yoy": False,
        "category": "注目銘柄",
    },
    "三菱重工（7011）": {
        "source": "yfinance",
        "ticker": "7011.T",
        "unit": "円",
        "yoy": False,
        "category": "注目銘柄",
    },
    "任天堂（7974）": {
        "source": "yfinance",
        "ticker": "7974.T",
        "unit": "円",
        "yoy": False,
        "category": "注目銘柄",
    },
    "UST 2Y": {
        "source": "fred",
        "ticker": "DGS2",
        "unit": "%",
        "yoy": False,
        "category": "金利",
    },
    "UST 10Y": {
        "source": "fred",
        "ticker": "DGS10",
        "unit": "%",
        "yoy": False,
        "category": "金利",
    },
    "UST 30Y": {
        "source": "fred",
        "ticker": "DGS30",
        "unit": "%",
        "yoy": False,
        "category": "金利",
    },
    "JGB 2Y": {
        "source": "mof_jgb",
        "ticker": "2年",
        "unit": "%",
        "yoy": False,
        "category": "金利",
    },
    "JGB 10Y": {
        "source": "mof_jgb",
        "ticker": "10年",
        "unit": "%",
        "yoy": False,
        "category": "金利",
    },
    "JGB 30Y": {
        "source": "mof_jgb",
        "ticker": "30年",
        "unit": "%",
        "yoy": False,
        "category": "金利",
    },
    "日米金利差 2Y（米国−日本）": {
        "source": "us_jp_yield_spread",
        "ticker": "2Y",
        "unit": "pt",
        "yoy": False,
        "category": "金利",
    },
    "日米金利差 10Y（米国−日本）": {
        "source": "us_jp_yield_spread",
        "ticker": "10Y",
        "unit": "pt",
        "yoy": False,
        "category": "金利",
    },
    "日米金利差 30Y（米国−日本）": {
        "source": "us_jp_yield_spread",
        "ticker": "30Y",
        "unit": "pt",
        "yoy": False,
        "category": "金利",
    },
    "情報技術（XLK）": {
        "source": "yfinance",
        "ticker": "XLK",
        "unit": "米ドル",
        "yoy": False,
        "category": "米国セクター",
    },
    "金融（XLF）": {
        "source": "yfinance",
        "ticker": "XLF",
        "unit": "米ドル",
        "yoy": False,
        "category": "米国セクター",
    },
    "ヘルスケア（XLV）": {
        "source": "yfinance",
        "ticker": "XLV",
        "unit": "米ドル",
        "yoy": False,
        "category": "米国セクター",
    },
    "一般消費財（XLY）": {
        "source": "yfinance",
        "ticker": "XLY",
        "unit": "米ドル",
        "yoy": False,
        "category": "米国セクター",
    },
    "生活必需品（XLP）": {
        "source": "yfinance",
        "ticker": "XLP",
        "unit": "米ドル",
        "yoy": False,
        "category": "米国セクター",
    },
    "資本財・サービス（XLI）": {
        "source": "yfinance",
        "ticker": "XLI",
        "unit": "米ドル",
        "yoy": False,
        "category": "米国セクター",
    },
    "エネルギー（XLE）": {
        "source": "yfinance",
        "ticker": "XLE",
        "unit": "米ドル",
        "yoy": False,
        "category": "米国セクター",
    },
    "素材（XLB）": {
        "source": "yfinance",
        "ticker": "XLB",
        "unit": "米ドル",
        "yoy": False,
        "category": "米国セクター",
    },
    "公益事業（XLU）": {
        "source": "yfinance",
        "ticker": "XLU",
        "unit": "米ドル",
        "yoy": False,
        "category": "米国セクター",
    },
    "不動産（XLRE）": {
        "source": "yfinance",
        "ticker": "XLRE",
        "unit": "米ドル",
        "yoy": False,
        "category": "米国セクター",
    },
    "コミュニケーション・サービス（XLC）": {
        "source": "yfinance",
        "ticker": "XLC",
        "unit": "米ドル",
        "yoy": False,
        "category": "米国セクター",
    },
    "中国：上海総合指数": {
        "source": "yfinance",
        "ticker": "000001.SS",
        "unit": "ポイント",
        "yoy": False,
        "category": "マーケット",
        "fallbacks": [
            {
                "source": "yfinance",
                "ticker": "ASHR",
                "unit": "米ドル",
                "label": "中国A株ETF（近似）",
            }
        ],
    },
    "インド：NIFTY 50": {
        "source": "yfinance",
        "ticker": "^NSEI",
        "unit": "ポイント",
        "yoy": False,
        "category": "マーケット",
        "fallbacks": [
            {
                "source": "yfinance",
                "ticker": "INDA",
                "unit": "米ドル",
                "label": "インド株ETF（近似）",
            }
        ],
    },
    "ベトナム：VN-Index": {
        "source": "yfinance",
        "ticker": "0P0000HY8X.VN",
        "unit": "ポイント",
        "yoy": False,
        "category": "マーケット",
        "fallbacks": [
            {
                "source": "yfinance",
                "ticker": "VNM",
                "unit": "米ドル",
                "label": "ベトナム株ETF（近似）",
            }
        ],
    },
    "ドイツ：DAX": {
        "source": "yfinance",
        "ticker": "^GDAXI",
        "unit": "ポイント",
        "yoy": False,
        "category": "マーケット",
        "fallbacks": [
            {
                "source": "yfinance",
                "ticker": "EWG",
                "unit": "米ドル",
                "label": "ドイツ株ETF（近似）",
            }
        ],
    },
    "スペイン：IBEX 35": {
        "source": "yfinance",
        "ticker": "^IBEX",
        "unit": "ポイント",
        "yoy": False,
        "category": "マーケット",
        "fallbacks": [
            {
                "source": "yfinance",
                "ticker": "EWP",
                "unit": "米ドル",
                "label": "スペイン株ETF（近似）",
            }
        ],
    },
    "ポーランド：NASDAQ Poland": {
        "source": "fred",
        "ticker": "NASDAQNQPL",
        "unit": "ポイント",
        "yoy": False,
        "category": "マーケット",
        "fallbacks": [
            {
                "source": "yfinance",
                "ticker": "EPOL",
                "unit": "米ドル",
                "label": "ポーランド株ETF（近似）",
            }
        ],
    },
    "メキシコ：S&P/BMV IPC": {
        "source": "yfinance",
        "ticker": "^MXX",
        "unit": "ポイント",
        "yoy": False,
        "category": "マーケット",
        "fallbacks": [
            {
                "source": "yfinance",
                "ticker": "EWW",
                "unit": "米ドル",
                "label": "メキシコ株ETF（近似）",
            }
        ],
    },
    "オーストラリア：S&P/ASX 200": {
        "source": "yfinance",
        "ticker": "^AXJO",
        "unit": "ポイント",
        "yoy": False,
        "category": "マーケット",
        "fallbacks": [
            {
                "source": "yfinance",
                "ticker": "EWA",
                "unit": "米ドル",
                "label": "オーストラリア株ETF（近似）",
            }
        ],
    },
}
