INDICATORS = {
    "CPI": {
        "source": "fred",
        "ticker": "CPIAUCSL",
        "unit": "指数",
        "yoy": True,
        "category": "経済指標",
    },
    "FF金利": {
        "source": "fred",
        "ticker": "FEDFUNDS",
        "unit": "%",
        "yoy": False,
        "category": "経済指標",
    },
    "失業率": {
        "source": "fred",
        "ticker": "UNRATE",
        "unit": "%",
        "yoy": False,
        "category": "経済指標",
    },
    "USD/JPY": {
        "source": "yfinance",
        "ticker": "JPY=X",
        "unit": "円",
        "yoy": False,
        "category": "為替",
    },
    "日経平均株価": {
        "source": "yfinance",
        "ticker": "^N225",
        "unit": "円",
        "yoy": False,
        "category": "マーケット",
    },
    "日経平均先物": {
        "source": "yfinance",
        "ticker": "NKD=F",
        "unit": "円",
        "yoy": False,
        "category": "マーケット",
    },
    "S&P 500指数": {
        "source": "yfinance",
        "ticker": "^GSPC",
        "unit": "ポイント",
        "yoy": False,
        "category": "マーケット",
    },
    "SOX指数": {
        "source": "yfinance",
        "ticker": "^SOX",
        "unit": "ポイント",
        "yoy": False,
        "category": "マーケット",
    },
    "VIX指数": {
        "source": "yfinance",
        "ticker": "^VIX",
        "unit": "ポイント",
        "yoy": False,
        "category": "マーケット",
    },
    "WTI原油先物": {
        "source": "yfinance",
        "ticker": "CL=F",
        "unit": "米ドル",
        "yoy": False,
        "category": "マーケット",
    },
    "BTCｰJPY": {
        "source": "yfinance",
        "ticker": "BTC-JPY",
        "unit": "円",
        "yoy": False,
        "category": "マーケット",
    },
    "EUR/JPY": {
        "source": "yfinance",
        "ticker": "EURJPY=X",
        "unit": "円",
        "yoy": False,
        "category": "為替",
    },
    "AUD/JPY": {
        "source": "yfinance",
        "ticker": "AUDJPY=X",
        "unit": "円",
        "yoy": False,
        "category": "為替",
    },
    "MXN/JPY": {
        "source": "yfinance",
        "ticker": "MXNJPY=X",
        "unit": "円",
        "yoy": False,
        "category": "為替",
    },
    "キオクシア（285A）": {
        "source": "yfinance",
        "ticker": "285A.T",
        "unit": "円",
        "yoy": False,
        "category": "注目銘柄",
    },
    "東京エレクトロン（8035）": {
        "source": "yfinance",
        "ticker": "8035.T",
        "unit": "円",
        "yoy": False,
        "category": "注目銘柄",
    },
    "レーザーテック（6920）": {
        "source": "yfinance",
        "ticker": "6920.T",
        "unit": "円",
        "yoy": False,
        "category": "注目銘柄",
    },
    "ディスコ（6146）": {
        "source": "yfinance",
        "ticker": "6146.T",
        "unit": "円",
        "yoy": False,
        "category": "注目銘柄",
    },
    "アドバンテスト（6857）": {
        "source": "yfinance",
        "ticker": "6857.T",
        "unit": "円",
        "yoy": False,
        "category": "注目銘柄",
    },
    "三菱商事（8058）": {
        "source": "yfinance",
        "ticker": "8058.T",
        "unit": "円",
        "yoy": False,
        "category": "注目銘柄",
    },
    "三菱UFJ（8306）": {
        "source": "yfinance",
        "ticker": "8306.T",
        "unit": "円",
        "yoy": False,
        "category": "注目銘柄",
    },
    "三菱重工（7011）": {
        "source": "yfinance",
        "ticker": "7011.T",
        "unit": "円",
        "yoy": False,
        "category": "注目銘柄",
    },
    "任天堂（7974）": {
        "source": "yfinance",
        "ticker": "7974.T",
        "unit": "円",
        "yoy": False,
        "category": "注目銘柄",
    },
    "UST 2Y": {
        "source": "fred",
        "ticker": "DGS2",
        "unit": "%",
        "yoy": False,
        "category": "金利",
    },
    "UST 10Y": {
        "source": "fred",
        "ticker": "DGS10",
        "unit": "%",
        "yoy": False,
        "category": "金利",
    },
    "UST 30Y": {
        "source": "fred",
        "ticker": "DGS30",
        "unit": "%",
        "yoy": False,
        "category": "金利",
    },
    "JGB 2Y": {
        "source": "mof_jgb",
        "ticker": "2年",
        "unit": "%",
        "yoy": False,
        "category": "金利",
    },
    "JGB 10Y": {
        "source": "mof_jgb",
        "ticker": "10年",
        "unit": "%",
        "yoy": False,
        "category": "金利",
    },
    "JGB 30Y": {
        "source": "mof_jgb",
        "ticker": "30年",
        "unit": "%",
        "yoy": False,
        "category": "金利",
    },
}
