INDICATORS = {
    "CPI": {
        "source": "fred",
        "ticker": "CPIAUCSL",
        "unit": "指数",
        "yoy": True,
        "category": "経済指標",
    },
    "FF金利": {
        "source": "fred",
        "ticker": "FEDFUNDS",
        "unit": "%",
        "yoy": False,
        "category": "経済指標",
    },
    "失業率": {
        "source": "fred",
        "ticker": "UNRATE",
        "unit": "%",
        "yoy": False,
        "category": "経済指標",
    },
    "ドル円": {
        "source": "yfinance",
        "ticker": "JPY=X",
        "unit": "円",
        "yoy": False,
        "category": "為替",
    },
    "日経平均株価": {
        "source": "yfinance",
        "ticker": "^N225",
        "unit": "円",
        "yoy": False,
        "category": "マーケット",
    },
    "日経平均先物": {
        "source": "yfinance",
        "ticker": "NKD=F",
        "unit": "円",
        "yoy": False,
        "category": "マーケット",
    },
    "S&P 500指数": {
        "source": "yfinance",
        "ticker": "^GSPC",
        "unit": "ポイント",
        "yoy": False,
        "category": "マーケット",
    },
    "SOX指数": {
        "source": "yfinance",
        "ticker": "^SOX",
        "unit": "ポイント",
        "yoy": False,
        "category": "マーケット",
    },
    "VIX指数": {
        "source": "yfinance",
        "ticker": "^VIX",
        "unit": "ポイント",
        "yoy": False,
        "category": "マーケット",
    },
    "WTI原油先物": {
        "source": "yfinance",
        "ticker": "CL=F",
        "unit": "米ドル",
        "yoy": False,
        "category": "マーケット",
    },
    "BTCｰJPY": {
        "source": "yfinance",
        "ticker": "BTC-JPY",
        "unit": "円",
        "yoy": False,
        "category": "マーケット",
    },
    "EUR/JPY": {
        "source": "yfinance",
        "ticker": "EURJPY=X",
        "unit": "円",
        "yoy": False,
        "category": "為替",
    },
    "AUD/JPY": {
        "source": "yfinance",
        "ticker": "AUDJPY=X",
        "unit": "円",
        "yoy": False,
        "category": "為替",
    },
    "MXN/JPY": {
        "source": "yfinance",
        "ticker": "MXNJPY=X",
        "unit": "円",
        "yoy": False,
        "category": "為替",
    },
}
